- name: play-1
  hosts: localhost
  become: yes
  tasks:
  - name: play-1 and task-1
    ansible.builtin.debug:
      msg: "hello from play-1 and task-1"

- name: play-1
  hosts: localhost
  become: yes
  tasks:
  - name: play-2 and task-2
    ansible.builtin.debug:
      msg: "hello from play-2 and task-2"
