- name: variable from play level
  hosts: localhost
  vars:
    Course: "Devops"
    trainer: "Vihari"
    duration: "2 months"
  become: yes
  tasks:
  - name: show variables
    vars:
      duration: "3 months"
    ansible.builtin.debug:
      msg: "I am learning {{ Course }}, my trainer is {{ trainer }} and course duration is {{ duration }}."
