- name: loop in ansible
  hosts: localhost
  become: yes

  tasks:
  - name: loop through a list
    ansible.builtin.package:
      name: "{{ item }}"
      state: present

      loop:
      - Docker

  - name: check whether installed or not 
    ansible.builtin.command:
      cmd: docker --version
      msg: "Docker is installed"
