- name: loop in ansible
  hosts: localhost
  become: yes

  tasks:
  - name: loop through a list
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - docker

  - name: check whether installed or not 
    ansible.builtin.command:
      cmd: docker --version && echo -e "Docker is installed"
