- name: loop in ansible
  hosts: localhost
  become: yes

  tasks:
  - name: loop through a list
    ansible.builtin.package:
      name: "{{ item }}"
      state: present

    loop:
      - Docker
  - name: check whether installed or not
    when: user.rc == 0
    ansible.builtin.debug:
      msg: "{{ item }} is installed"
      